---
name: Run tests

on:
  push:
    branches:
      - 'dev'

jobs:
  test1:
    name: Just test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start testing
        run: echo "Starting tests"
